export const products = [
  { id: 0, 
    name: 'ปลาปีรันย่า', 
    price: 500, 
    imageId: 'MK3eW3A' },
  { id: 1, 
    name: 'ปลาไหลไฟฟ้า', 
    price: 1500, 
    imageId: 'mynHUSa' },
  { id: 2, 
    name: 'ปลาบู่', 
    price: 180, 
    imageId: 'bE7W1ji' },
  { id: 3, 
    name: 'ปลาทอง', 
    price: 220, 
    imageId: 'IOjWm71' },
  { id: 4, 
    name: 'ปลาคราฟ', 
    price: 1000, 
    imageId: 'lrWQx8l' },
  { id: 5, 
    name: 'ปลาดุก', 
    price: 300, 
    imageId: 'XY7eW2A' },
  { id: 6, 
    name: 'ปลาฉลาม',
    price: 3500, 
    imageId: 'UJ3nX8L' },
  { id: 7, 
    name: 'ปลาหางนกยูง', 
    price: 120, 
    imageId: 'PQ9kZ4B' },
  { id: 8, 
    name: 'ปลาตีน', 
    price: 180, 
    imageId: 'QZ2jW5N' },
  { id: 9, 
    name: 'ปลากระเบน', 
    price: 900, 
      imageId: 'BC8kW4P' }
];

// data.js
